# Generated by Django 4.2.16 on 2025-06-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_message_forward_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_pin',
            field=models.BooleanField(default=False),
        ),
    ]
